export const CLASSROOM_TIME_SCHEMA_VERSION = 1 as const;

export const MAX_CLASSROOM_TIME_WIDGETS = 64;
export const MAX_ACTIVE_ALARM_JOBS = 32;
export const MAX_CLASSROOM_TIME_LABEL_LENGTH = 80;
export const MAX_CALENDAR_EVENT_TITLE_LENGTH = 120;
export const MAX_CALENDAR_EVENT_NOTE_LENGTH = 1_000;
export const MAX_CALENDAR_EVENTS_PER_LAYER = 500;
export const MAX_CALENDAR_TRANSFER_CACHE_BYTES = 512 * 1024;

export const MIN_TIMER_DURATION_MS = 1_000;
export const MAX_TIMER_DURATION_MS = ((99 * 60 + 59) * 60 + 59) * 1_000;
export const ALARM_REPEAT_INTERVAL_MS = 10_000;
export const MAX_ALARM_REPEAT_WINDOW_MS = 60_000;

export const SAFE_HEX_COLOR_PATTERN = /^#[0-9a-fA-F]{6}$/;
